=== xbrles/pgc2007/resources/System/Metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 The contents of this file are subject to the UBmatrix License Version 1.0 (the "License");
 you may not use this file except in compliance with the License. You may obtain a copy of the
 License at http://www.ubmatrix.com/prospect/eula_processor.asp

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 Copyright (c) UBmatrix, Inc., 2005-2006.  All Rights Reserved.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xs:simpleType name="ConditionSetFailEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="NotEmpty"/>
			<xs:enumeration value="Empty"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="BooleanTypeEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="True"/>
			<xs:enumeration value="False"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ArgumentSelectorTypeEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="DomainObject"/>
			<xs:enumeration value="Relationship"/>
			<xs:enumeration value="SchemaVOUri"/>
			<xs:enumeration value="String"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="InstructionType">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="DomainObjectSelector" type="SelectorType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="ConstantSelector" type="SelectorType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="DtsQuerySelector" type="SelectorType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="RunMethod" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="DTSAddReferencedLocation" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="doUri" type="xs:token" use="optional"/>
		<xs:attribute name="voUri" type="xs:token" use="optional"/>
		<xs:attribute name="name" type="xs:token" use="optional"/>
		<xs:attribute name="saveDO" type="xs:token" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ConditionSetInstructionType">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="DomainObjectSelector" type="SelectorType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="ConstantSelector" type="SelectorType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="DtsQuerySelector" type="SelectorType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="RunMethod" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="RemoveDomainObject" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>				
			</xs:choice>
			<xs:element name="Failure" type="ConditionSetSuccessAndFailureType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Success" type="ConditionSetSuccessAndFailureType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Return" type="ReturnType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="doUri" type="xs:token" use="optional"/>
		<xs:attribute name="voUri" type="xs:token" use="optional"/>
		<xs:attribute name="name" type="xs:token" use="optional"/>
		<xs:attribute name="testValue" type="xs:token" use="optional"/>
		<xs:attribute name="Fail" type="ConditionSetFailEnumeration" use="optional"/>
		<xs:attribute name="saveDO" type="xs:token" use="optional"/>
	</xs:complexType>
	<xs:complexType name="FailureType">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="CreateMemo" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="CreateDomainObject" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SelectorType">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="DomainObjectSelector" type="SelectorType" maxOccurs="unbounded"/>
				<xs:element name="ConstantSelector" type="SelectorType" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="value" type="xs:token" use="optional"/>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="saveDO" type="xs:token" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ArgumentSelectorType">
		<xs:attribute name="value" type="xs:token" use="optional"/>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="type" type="ArgumentSelectorTypeEnumeration" use="required"/>
		<xs:attribute name="allowNull" type="BooleanTypeEnumeration" use="required"/>
	</xs:complexType>
	<xs:complexType name="ConditionSetSuccessAndFailureType">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="CreateMemo" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="CreateRelationship" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="CreateDomainObject" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="RemoveDomainObject" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="DtsQuerySelector" type="SelectorType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="RunMethod" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="ConditionSet" type="ConditionSetInstructionType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DTSQueryType">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="DomainObjectSelector" type="SelectorType" maxOccurs="unbounded"/>
				<xs:element name="ConstantSelector" type="SelectorType" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:element name="Failure" type="FailureType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReturnType">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="DomainObjectSelector" type="SelectorType" maxOccurs="unbounded"/>
				<xs:element name="DtsQuerySelector" type="SelectorType" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MethodType">
		<xs:sequence>
			<xs:element name="DomainObjectArgumentSelector" type="ArgumentSelectorType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ConstantArgumentSelector" type="SelectorType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="ConditionSet" type="ConditionSetInstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="CreateDomainObject" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="CreateRelationship" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="RemoveRelationship" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="RemoveDomainObject" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="DtsQuerySelector" type="SelectorType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="RunMethod" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="DTSAddReferencedLocation" type="InstructionType" minOccurs="0" maxOccurs="unbounded"/>				
			</xs:choice>
			<xs:element name="Return" type="ReturnType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:token" use="optional"/>
		<xs:attribute name="behaviorUri" type="xs:token" use="required"/>
	</xs:complexType>
	<xs:element name="MethodSet">
		<xs:annotation>
			<xs:documentation>The Metadata for Editing</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Method" type="MethodType" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:token" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== xbrles/pgc2007/resources/System/TaxonomyMetadata.xml
<?xml version="1.0" encoding="utf-8"?>
<MethodSet name="EditingPattern" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Metadata.xsd">	
	<!-- TAXONOMY -->
	<Method name="SetSubstitutionGroup" behaviorUri="behavior://ubmatrix.com/Xbrl/Taxonomy#Concept.SetSubstitutionGroup">
		<DomainObjectArgumentSelector name="conceptDO" value="." type="DomainObject" allowNull="False"/> 		
		<DomainObjectArgumentSelector name="substitutionGroupDO" value="0" type="DomainObject" allowNull="False"/> 		
		<ConditionSet Fail="Empty" testValue="itemSubstitutionGroup">
			<!-- given substitutionGroupDO, check if the substituionGroup is a item or not -->		
			<DtsQuerySelector saveDO="itemSubstitutionGroup">			
				<DomainObjectSelector saveDO="startDO" value="substitutionGroupDO"/>
				<ConstantSelector value="IsClassifiedBy"/>				
				<ConstantSelector value="&amp;http://www.xbrl.org/2003/instance#item"/>				
			</DtsQuerySelector>			
			<Failure>
				<ConditionSet Fail="Empty" testValue="tupleConcept">
					<!-- given substitutionGroupDO, check if the substituionGroup is a tuple or not
					-->		
					<DtsQuerySelector saveDO="tupleConcept">			
						<DomainObjectSelector saveDO="startDO" value="substitutionGroupDO"/>
						<ConstantSelector value="IsClassifiedBy"/>				
						<ConstantSelector value="&amp;http://www.xbrl.org/2003/instance#tuple"/>				
					</DtsQuerySelector>			
					<Failure>
						<CreateMemo doUri="memo://ubmatrix.com/Edit/Taxonomy#SubstitutionGroupNotItemNorTuple">
							<DomainObjectSelector name="particle1" value="substitutionGroupDO"/>
						</CreateMemo>	
					</Failure>
					<Success>
						<RunMethod name="RemoveAttribute">
							<ConstantSelector saveDO="methodName" value="RemoveAttribute"/>
							<DomainObjectSelector saveDO="methodWorkingDO" value="conceptDO"/>
							<ConstantSelector saveDO="methodArg0" value="http://www.xbrl.org/2003/instance"/>
							<ConstantSelector saveDO="methodArg1" value="periodType"/>
						</RunMethod>
						<RunMethod name="RemoveAttribute">
							<ConstantSelector saveDO="methodName" value="RemoveAttribute"/>
							<DomainObjectSelector saveDO="methodWorkingDO" value="conceptDO"/>
							<ConstantSelector saveDO="methodArg1" value="abstract"/>
						</RunMethod>
						<RunMethod name="RemoveAttribute">
							<ConstantSelector saveDO="methodName" value="RemoveAttribute"/>
							<DomainObjectSelector saveDO="methodWorkingDO" value="conceptDO"/>
							<ConstantSelector saveDO="methodArg1" value="nillable"/>
						</RunMethod>
						<CreateRelationship doUri="relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#DefinedBySubstitutionGroup">
							<DomainObjectSelector saveDO="From" value="conceptDO"/>
							<DomainObjectSelector saveDO="To" value="substitutionGroupDO"/>
						</CreateRelationship>
					</Success>
				</ConditionSet>		
			</Failure>
			<Success>
				<RemoveDomainObject>
					<DtsQuerySelector saveDO="RemoveDomainObject">
						<DomainObjectSelector saveDO="startDO" value="conceptDO"/>
						<ConstantSelector value="/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#DefinedBySubstitutionGroup'"/>
					</DtsQuerySelector>
				</RemoveDomainObject>
				<CreateRelationship doUri="relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#DefinedBySubstitutionGroup">
					<DomainObjectSelector saveDO="From" value="conceptDO"/>
					<DomainObjectSelector saveDO="To" value="substitutionGroupDO"/>
				</CreateRelationship>
			</Success>
		</ConditionSet>		
	</Method>
	<Method name="SetDatatype" behaviorUri="behavior://ubmatrix.com/Xbrl/Taxonomy#Concept.SetDatatype">
		<DomainObjectArgumentSelector name="conceptDO" value="." type="DomainObject" allowNull="False"/> 		
		<DomainObjectArgumentSelector name="datatypeDO" value="0" type="DomainObject" allowNull="False"/> 		
		<RemoveDomainObject>
			<DtsQuerySelector saveDO="RemoveDomainObject">
				<DomainObjectSelector saveDO="startDO" value="conceptDO"/>
				<ConstantSelector value="/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#ConceptSpecifiesDatatype'"/>
			</DtsQuerySelector>
		</RemoveDomainObject>
		<CreateRelationship doUri="relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#ConceptSpecifiesDatatype">
			<DomainObjectSelector saveDO="From" value="conceptDO"/>
			<DomainObjectSelector saveDO="To" value="datatypeDO"/>
		</CreateRelationship>
	</Method>
	<Method name="RemoveConcept" behaviorUri="behavior://ubmatrix.com/Xbrl/Taxonomy#Taxonomy.RemoveConcept">
		<DomainObjectArgumentSelector name="taxonomyDO" value="." type="DomainObject" allowNull="False"/> 		
		<DomainObjectArgumentSelector name="conceptDO" value="0" type="DomainObject" allowNull="False"/> 		
		<RemoveDomainObject>
			<DtsQuerySelector saveDO="RemoveDomainObject">
				<DomainObjectSelector saveDO="startDO" value="conceptDO"/>
				<ConstantSelector value="/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#ConceptSpecifiesDatatype'"/>
			</DtsQuerySelector>
		</RemoveDomainObject>
		<RemoveDomainObject>
			<DtsQuerySelector saveDO="RemoveDomainObject">
				<DomainObjectSelector saveDO="startDO" value="conceptDO"/>
				<ConstantSelector value="/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#DefinedBySubstitutionGroup'"/>
			</DtsQuerySelector>
		</RemoveDomainObject>
		<RemoveDomainObject>
			<DtsQuerySelector saveDO="RemoveDomainObject">
				<DomainObjectSelector saveDO="startDO" value="taxonomyDO"/>
				<ConstantSelector value="/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#TaxonomySpecifiesConcept'"/>
				<DomainObjectSelector saveDO="toEndDO" value="conceptDO"/>
			</DtsQuerySelector>
		</RemoveDomainObject>
		<RemoveDomainObject>
			<DtsQuerySelector saveDO="RemoveDomainObjectSet">
				<DomainObjectSelector saveDO="startDO" value="conceptDO"/>
				<ConstantSelector value="/-'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#TupleContainsConcept'"/>
			</DtsQuerySelector>
		</RemoveDomainObject>
		<RemoveDomainObject>
			<DtsQuerySelector saveDO="RemoveDomainObjectSet">
				<DomainObjectSelector saveDO="startDO" value="conceptDO"/>
				<ConstantSelector value="/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#TupleContainsConcept'"/>
			</DtsQuerySelector>
		</RemoveDomainObject>
		<RemoveDomainObject>
			<DomainObjectSelector saveDO="RemoveDomainObject" value="conceptDO"/>
		</RemoveDomainObject>
	</Method>
</MethodSet>
<!--
 The contents of this file are subject to the UBmatrix License Version 1.0 (the "License");
 you may not use this file except in compliance with the License. You may obtain a copy of the
 License at http://www.ubmatrix.com/prospect/eula_processor.asp

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 Copyright (c) UBmatrix, Inc., 2005-2006.  All Rights Reserved.
-->
