=== xbrles/pgc2007/resources/System/ValidationPatterns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="unqualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- MSXML parser broken, currently not setting
     the default namespace
    xmlns:ps="http://www.ubmatrix.com/core/patternset"
    targetNamespace="http://www.ubmatrix.com/core/patternset"
-->
	<xs:simpleType name="patternMethodEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="DtsXPath"/>
			<xs:enumeration value="runOnce"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="actionMethodEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="CreateErrorMemo"/>
			<xs:enumeration value="ThrowException"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="selectorTypeEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="ValueObject"/>
			<xs:enumeration value="From"/>
			<xs:enumeration value="To"/>
			<xs:enumeration value="Prefix"/>
			<xs:enumeration value="Namespace"/>
			<xs:enumeration value="IgnoreWhenProcessing"/>
			<xs:enumeration value="LogicalUri"/>
			<xs:enumeration value="XmlBase"/>
			<xs:enumeration value="SchemaLocationPairs"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="queryPartMethodEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="XPath"/>
			<xs:enumeration value="Constant"/>
			<xs:enumeration value="NamespaceNode"/>
			<xs:enumeration value="Object"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="severityEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="fatalerror"/>
			<xs:enumeration value="error"/>
			<xs:enumeration value="warning"/>
			<xs:enumeration value="info"/>
			<xs:enumeration value="inconsistent"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="selectorMethodEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="Constant"/>
			<xs:enumeration value="XPath"/>
			<xs:enumeration value="DomainObject"/>
			<xs:enumeration value="DtsXPath"/>
			<xs:enumeration value="DtsXPath-ResolveNamespace"/>
			<xs:enumeration value="DtsFindSchemaDomainObject"/>
			<xs:enumeration value="DtsConstant"/>
			<xs:enumeration value="NamespaceNode"/>
			<xs:enumeration value="DtsXPathWithLogicalUriTranslateToPhysicalUri"/>
			<xs:enumeration value="DomainObjectFromValueObjectXPath"/>
			<xs:enumeration value="XPathWithTruncating"/>
			<xs:enumeration value="ReferencedDomainObject"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ComplexSelectorPartMethodEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="XPath"/>
			<xs:enumeration value="Constant"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="SelectorAttributeGroup">
		<xs:attribute name="method" type="selectorMethodEnumeration" use="required"/>
		<xs:attribute name="value" type="xs:token" use="required"/>
	</xs:attributeGroup>
	<xs:complexType name="SelectorType">
		<xs:attribute name="type" type="selectorTypeEnumeration" use="required"/>
		<xs:attribute name="method" type="selectorMethodEnumeration" use="required"/>
		<xs:attribute name="value" type="xs:token" use="required"/>
	</xs:complexType>
	<xs:complexType name="ComplexSelectorType">
		<xs:sequence>
			<xs:element name="SelectorPart" minOccurs="2" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="method" type="ComplexSelectorPartMethodEnumeration" use="required"/>
					<xs:attribute name="value" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="selectorTypeEnumeration" use="required"/>
		<xs:attribute name="method" type="selectorMethodEnumeration" use="required"/>
	</xs:complexType>
	<xs:complexType name="FailureSelectorType">
		<xs:attribute name="method" type="selectorMethodEnumeration" use="required"/>
		<xs:attribute name="value" type="xs:token" use="required"/>
	</xs:complexType>
	<xs:complexType name="FailureType">
		<xs:sequence>
			<xs:element name="Action" type="ActionType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="severity" type="severityEnumeration"/>
	</xs:complexType>
	<xs:complexType name="ActionType">
		<xs:sequence>
			<xs:element name="DtsQueryPredicate" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="QueryPart" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="method" type="queryPartMethodEnumeration" use="required"/>
								<xs:attribute name="value" type="xs:token" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="dtsRecursion" type="xs:boolean" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Selector" type="SelectorType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ComplexSelector" type="ComplexSelectorType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Failure" type="FailureType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:token" use="optional"/>
		<xs:attribute name="saveDO" type="xs:token" use="optional"/>
		<xs:attribute name="uri" type="xs:token" use="required"/>
		<xs:attribute name="method" type="xs:string" use="required"/>
		<xs:attribute name="indexByValueObject" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="PatternType">
		<xs:sequence>
			<xs:element name="Failure" type="FailureType" minOccurs="0"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="Action" type="ActionType"/>
				<xs:element name="Pattern" type="PatternType"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID"/>
		<xs:attribute name="name" type="xs:token" use="required"/>
		<xs:attribute name="method" type="patternMethodEnumeration" use="required"/>
		<xs:attribute name="value" type="xs:token" use="required"/>
		<xs:attribute name="processOverrides" type="xs:boolean" />
	</xs:complexType>
	<xs:element name="PatternSet">
		<xs:annotation>
			<xs:documentation>The Patterns for Validations</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pattern" type="PatternType" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:token" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

<!--
 The contents of this file are subject to the UBmatrix License Version 1.0 (the "License");
 you may not use this file except in compliance with the License. You may obtain a copy of the
 License at http://www.ubmatrix.com/prospect/eula_processor.asp

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 Copyright (c) UBmatrix, Inc., 2005-2006.  All Rights Reserved.
-->

=== xbrles/pgc2007/resources/System/XmlValidationPatternset.xml
<?xml version="1.0" encoding="utf-8" ?> 

<PatternSet
    name="XmlValidationPatterns"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ValidationPatterns.xsd" >
    <Pattern id="ValidateInstanceAgainstSchema" 
			name="ValidateInstanceAgainstSchema" 
			method="DtsXPath" 
			value="ValidateInstance()">			
         <Failure>
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#InstanceDocumentFailedToValidateAgainstSchema" />
         </Failure>
    </Pattern>     
    <!-- Removing because it is done during load. Once editing is enabled, we will add this back in
    <Pattern id="ValidateSchemaAgainstSchema" 
			name="ValidateSchemaAgainstSchema" 
			method="DtsXPath" 
			value="ValidateSchema()">			
         <Failure>
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#SchemaFailedToValidateAgainstSchema" />
         </Failure>
    </Pattern>         
    -->
    <Pattern id="ValidateTuplesMustNotUseMixedAttribute" 
    			name="ValidateTuplesMustNotUseMixedAttribute" 
    			method="DtsXPath" 
    			value="/'domain://ubmatrix.com/Xbrl/Taxonomy#TupleConcept'ValidateMixedAttribute()">      			      			
             <Failure severity="error">
                        <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#TuplesMustNotUseMixedAttribute" />
             </Failure>
    </Pattern>     
                
    <Pattern id="ValidateTuplesMustNotContainAnonymousDefinition" 
    			name="ValidateTuplesMustNotContainAnonymousDefinition" 
    			method="DtsXPath" 
    			value="/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#TupleContainsConcept'/'domain://ubmatrix.com/Xbrl/Taxonomy#LocalConcept'ValidateAnonymousDefinition()">    			
             <Failure>
                        <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#TuplesMustNotContainAnonymousDefinition" />
             </Failure>
    </Pattern>  
    
 
    
 </PatternSet>

<!--
 The contents of this file are subject to the UBmatrix License Version 1.0 (the "License");
 you may not use this file except in compliance with the License. You may obtain a copy of the
 License at http://www.ubmatrix.com/prospect/eula_processor.asp

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 Copyright (c) UBmatrix, Inc., 2005-2006.  All Rights Reserved.
-->

=== xbrles/pgc2007/resources/System/TaxonomyValidationPatternset.xml
<?xml version="1.0" encoding="utf-8" ?> 

<PatternSet

    name="TaxonomyValidationPatterns"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ValidationPatterns.xsd" >

    <!--Pattern id="ValidateTupleConceptMustNotHaveOtherThanConcept" 
			name="ValidateTupleConceptMustNotHaveOtherThanConcept" 
			method="DtsXPath" 
			value="/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#TupleContainsConcept'/'*'Exclude(domain://ubmatrix.com/Xbrl/Taxonomy#Concept)">			
         <Failure severity="error">
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#TupleConceptHasOtherThanConcept" />
         </Failure>
    </Pattern-->  
 
<!-- This is now commented but may be required in the best practices
    <Pattern id="ValidateTupleConceptMustNotBeEmpty" 
 			name="ValidateTupleConceptMustNotBeEmpty" 
 			method="DtsXPath" 
 			value="/'domain://ubmatrix.com/Xbrl/Taxonomy#TupleConcept'[not(hasPath(/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#TupleContainsConcept'))]">			
          <Failure severity="warning">
                     <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#TupleConceptIsEmpty" />
          </Failure>
    </Pattern>  
-->

    <!-- The spec says that we should check for concepts only , not to have duplicate id -->
    <!-- commenting this pattern as per cliff's mail 
    <Pattern id="DomainObjectHasUniqueID" 
			name="DomainObjectHasUniqueID" 
			method="DtsXPath" 
			value="/'domain://ubmatrix.com/Xbrl/Taxonomy#Concept'!DomainObjectHasUniqueID()">			
         <Failure severity="warning">
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#DomainObjectDoesNotHaveUniqueID" />
         </Failure>
    </Pattern>  
   -->
 
    <Pattern id="ValidateRelationshipEndpoints" 
			name="ValidateRelationshipEndpoints" 
			method="DtsXPath" 
			value="RelationshipHasValidEndpoints()">			
         <Failure severity="error">
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#InvalidRelationshipEndpoint" />
         </Failure>
    </Pattern>  
 
    <Pattern id="ValidateRelationshipEndpointCardinality" 
			name="ValidateRelationshipEndpointCardinality" 
			method="DtsXPath" 
			value="RelationshipHasValidEndpointCardinality()">			
         <Failure severity="error">
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#InvalidRelationshipEndpointCardinality" />
         </Failure>
    </Pattern> 

    <Pattern id="vr_215" 
			name="ValidateTupleAttributesNotDefinedInXBRLNamespace" 
			method="DtsXPath" 
			value="/'domain://ubmatrix.com/Xbrl/Instance#TupleFact'ValidateTupleAttributesNotDefinedInXBRLNamespace()">			
         <Failure severity="error">
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#TupleAttributesDefinedInXBRLNamespce" />
         </Failure>
    </Pattern>
  

    <Pattern id="vr_215_1" 
			name="ValidateTupleDoesNotHavePeriodTypeAttribute" 
			method="DtsXPath" 
			value="/'domain://ubmatrix.com/Xbrl/Taxonomy#TupleConcept'[hasAttr('http://www.xbrl.org/2003/instance#periodType')]">			
         <Failure severity="error">
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#TupleContainsPeriodTypeAttribute" />
         </Failure>
    </Pattern>

    <Pattern id="vr_215_2" 
			name="ValidateTupleDoesNotHaveBalanceAttribute" 
			method="DtsXPath" 
			value="/'domain://ubmatrix.com/Xbrl/Taxonomy#TupleConcept'[hasAttr('http://www.xbrl.org/2003/instance#balance')]">			
         <Failure severity="error">
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#TupleContainsBalanceAttribute" />
         </Failure>
    </Pattern>   

    <Pattern id="vr_250" 
			name="ValidateNonMonetaryItemTypeMustNotHaveBalanceAttribute" 
			method="DtsXPath" 
			value="/'domain://ubmatrix.com/Xbrl/Taxonomy#ItemConcept'[hasAttr('http://www.xbrl.org/2003/instance#balance')]!IsMonetary()">			
         <Failure severity="error">
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#NonMonetaryItemTypeMustNotHaveBalanceAttribute" />
         </Failure>
    </Pattern>     
    
    
    <Pattern id="vr_252" 
			name="ValidateItemTypesMustBeXbrlDataType" 
			method="DtsXPath" 
			value="/'domain://ubmatrix.com/Xbrl/Taxonomy#ItemConcept'!IsXbrlDataType()">			
         <Failure severity="error">
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#ItemTypesMustBeXbrlDataType" />
         </Failure>
    </Pattern> 
    
    
    <Pattern id="vr_246_item" 
			name="ValidateItemSubstitutionGroupHasPeriodTypeAttribute" 
			method="DtsXPath" 
			value="/'domain://ubmatrix.com/Xbrl/Taxonomy#ItemConcept'[not(hasAttr('http://www.xbrl.org/2003/instance#periodType'))]">			
         <Failure severity="error">
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#ItemTypesMustHavePeriodAttribute" />
         </Failure>
    </Pattern>    


    <!-- changed: value="/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#ConceptSpecifiesDatatype'/'domain://ubmatrix.com/Xbrl/Taxonomy#Datatype'[hasAttr('id')]"> -->
    <!-- value="/'domain://ubmatrix.com/Xbrl/Taxonomy#Concept'[not(hasAttr('id'))]"> -->
    <!-- value="/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#ConceptSpecifiesDatatype'/'domain://ubmatrix.com/Xbrl/Taxonomy#Datatype'[hasAttr('id')]"> -->

    <Pattern id="vr_243" 
			name="ValidateConceptDefinitionHasID" 
			method="DtsXPath" 
			value="/'domain://ubmatrix.com/Xbrl/Taxonomy#Concept'[not(hasAttr('id'))]">			
			
         <Failure severity="warning">
                    <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#ConceptDefinitionDoesNotHaveID" />
         </Failure>
    </Pattern>  
    

    <Pattern id="CB_Conformance_104-17"
			name="TuplesMustNotSpecifyNestedAnonymousTypes" 
			method="DtsXPath" 
			value="/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#TupleContainsConcept'/'domain://ubmatrix.com/Xbrl/Taxonomy#LocalTupleConcept'/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#ConceptSpecifiesDatatype'/'domain://ubmatrix.com/Xbrl/Taxonomy#AnonymousComplexDatatype'">
         <Failure severity="error">
             <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#TuplesMustNotSpecifyNestedAnonymousTypes" />
         </Failure>
    </Pattern>  
    

    <!-- open issue -->
    <!--
    <Pattern id="SC_Conformance_104-09-10"
    		name="TuplesMustNotHaveInvalidAtribute" 
    		method="DtsXPath" 
    		value="/'domain://ubmatrix.com/Xbrl/Instance#Fact'[/-'relationship://ubmatrix.com/Xbrl/Instance/Relationship#ConceptDefinesFact'/'domain://ubmatrix.com/Xbrl/Taxonomy#TupleConcept']ValidateTupleAttribute()">
         <Failure severity="error">
               <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#TuplesHaveInvalidAttribute" />
         </Failure>
    </Pattern>  
    -->



    <Pattern id="vr_roleDeclared" 
    			name="ValidateRoleEquivalency" 
    			method="DtsXPath" 
    			value="/'domain://ubmatrix.com/Xbrl/Taxonomy#Role'ValidateRoleEquivalency()">
             <Failure severity="error">
                        <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Linkbase#InvalidUsedOnElements" />
             </Failure>
    </Pattern>       
    
    
    <Pattern id="ValidateNonEmptyTargetNamespace" 
          			name="ValidateNonEmptyTargetNamespace" 
          			method="DtsXPath"           			
          			value="/'domain://ubmatrix.com/Xbrl/Taxonomy#Taxonomy'/+'relationship://ubmatrix.com/Xbrl/Taxonomy/Relationship#TaxonomyDefinedByTargetNamespace'/'domain://ubmatrix.com/Xbrl/Namespace#Namespace'[value() == '']">      			      
                   <Failure severity="error">
                              <Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Validation/Taxonomy#EmptyTargetNamespace" />
                   </Failure>
    </Pattern>
    
 </PatternSet>

<!--
 The contents of this file are subject to the UBmatrix License Version 1.0 (the "License");
 you may not use this file except in compliance with the License. You may obtain a copy of the
 License at http://www.ubmatrix.com/prospect/eula_processor.asp

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 Copyright (c) UBmatrix, Inc., 2005-2006.  All Rights Reserved.
-->

=== xbrles/pgc2007/resources/System/InstanceDimensionValidationPatternset.xml
<?xml version="1.0" encoding="utf-8" ?> 

<PatternSet

    name="Instance Dimension Validation Patterns"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ValidationPatterns.xsd" >

    <!-- 3.1.1

			A primary item is dimensionally valid in the hypercubes found in at least one base set are mutually valid. 
			See 3.1.2 below, "Mutual validity of hypercubes in a base set". A dimensional processor MUST raise an error [Ins Err, 2] 			
			xbrldie:PrimaryItemDimensionallyInvalidError if the hypercube combinations found in all base sets are invalid.

	        Note:The mutual validity of hypercubes in a base set and validity of dimensions is performed during validation of
            the primary items.
     -->
    <Pattern id="xbrldie_PrimaryItemDimensionallyInvalidError"
             name="xbrldie:PrimaryItemDimensionallyInvalidError"
             method="DtsXPath"
             value="test_xbrldie_primaryitemdimensionallyinvaliderror()">
          <Failure severity="error">
                <Action saveDO="memo" method="CreateErrorMemo" uri="http://xbrl.org/2005/xbrldie/errors#PrimaryItemDimensionallyInvalidError" />
          </Failure>
    </Pattern>  

	<!-- 3.1.4

	A context MUST NOT contain more than one dimension value for each dimension. A validator MUST signal [Ins Err, 3] 
	xbrldie:RepeatedDimensionInInstanceError when this rule is violated.	
-->
    <Pattern id="xbrldie_Test_Xbrldie_RepeatedDimensionInInstance"
             name="xbrldie:Test_Xbrldie_RepeatedDimensionInInstance"
             method="DtsXPath"
             value="test_xbrldie_repeateddimensionininstance()">
          <Failure severity="error">
                <Action saveDO="memo" method="CreateErrorMemo" uri="http://xbrl.org/2005/xbrldie/errors#RepeatedDimensionInInstanceError" />
          </Failure>
    </Pattern>  

	<!-- 2.8.1

	The default value of a dimension MUST NOT be reported in an instance. A dimensional processor MUST raise [Ins Err, 1]	 		
	xbrldie:DefaultValueUsedInInstanceError when a default value is explicitly reported.
	-->
    <Pattern id="xbrldie_Test_Xbrldie_DefaultValueUsedInInstance"
             name="xbrldie:Test_Xbrldie_DefaultValueUsedInInstance"
             method="DtsXPath"
             value="test_xbrldie_defaultvalueusedininstance()">
          <Failure severity="error">
                <Action saveDO="memo" method="CreateErrorMemo" uri="http://xbrl.org/2005/xbrldie/errors#DefaultValueUsedInInstanceError" />
          </Failure>
    </Pattern>  

	<!-- 3.1.4.4.2

	The content of the dimension attribute of an xbrldi:typedMember element MUST be the 
	QName of a typed dimension declaration [Def, 6] defined in a schema within the DTS of the 
	instance document. A dimensional processor MUST raise an error [Ins Err, 4] xbrldie:TypedMemberNotTypedDimensionError 
	if the element whose QName appears in the dimension attribute of xbrldi:explicitMember resolves to anything 
	other than a typed dimension declaration [Def, 6].
	-->
    <Pattern id="xbrldie_Test_Xbrldie_TypedMemberNotTypedDimension"
             name="xbrldie:Test_Xbrldie_TypedMemberNotTypedDimension"
             method="DtsXPath"
             value="test_xbrldie_typedmembernottypeddimension()">
          <Failure severity="error">
                <Action saveDO="memo" method="CreateErrorMemo" uri="http://xbrl.org/2005/xbrldie/errors#TypedMemberNotTypedDimensionError" />
          </Failure>
    </Pattern>  

	<!-- 3.1.4.5.2

	The content of the dimension attribute of an xbrldi:explicitMember element MUST be the QName of an 
	explicit dimension element [Def, 7] defined in a schema within the DTS of the instance document. A 
	dimensional processor MUST raise an error [Ins Err, 5] xbrldie:ExplicitMemberNotExplicitDimensionError 
	if the element whose QName appears in the dimension attribute of xbrldi:explicitMember resolves to anything other than an explicit dimension 
	declaration [Def, 7].
	-->
    <Pattern id="xbrldie_Test_Xbrldie_ExplicitMemberNotExplicitDimension"
             name="xbrldie:Test_Xbrldie_ExplicitMemberNotExplicitDimension"
             method="DtsXPath"
             value="test_xbrldie_explicitmembernotexplicitdimension()">
          <Failure severity="error">
                <Action saveDO="memo" method="CreateErrorMemo" uri="http://xbrl.org/2005/xbrldie/errors#ExplicitMemberNotExplicitDimensionError" />
          </Failure>
    </Pattern>  

	<!-- 3.1.4.5.3

	element definition can be found in the taxonomy schema referenced by the namespace of the QName. 
	A dimensional processor MUST raise en error [Ins Err, 6] xbrldie:ExplicitMemberUndefinedQNameError if this rule is violated.
	-->
    <Pattern id="xbrldie_Test_Xbrldie_ExplicitMemberUndefinedQNameError"
             name="xbrldie:Test_Xbrldie_ExplicitMemberUndefinedQNameError"
             method="DtsXPath"
             value="test_xbrldie_explicitmemberundefinedqnameerror()">
          <Failure severity="error">
                <Action saveDO="memo" method="CreateErrorMemo" uri="http://xbrl.org/2005/xbrldie/errors#ExplicitMemberUndefinedQNameError" />
          </Failure>
    </Pattern>  

<!-- Test all aggregations found in the DTS -->
    <Pattern id="xbrldie_Test_Xbrldie_Aggregation" 
			name="xbrldie_Test_Xbrldie_Aggregation" 
			method="DtsXPath" 
			value="/'domain://ubmatrix.com/Xbrl/Taxonomy#Role'HasInvalidAggregation()">
         <Failure severity="error" />
    </Pattern>

</PatternSet>
<!--
 The contents of this file are subject to the UBmatrix License Version 1.0 (the "License");
 you may not use this file except in compliance with the License. You may obtain a copy of the
 License at http://www.ubmatrix.com/prospect/eula_processor.asp

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 Copyright (c) UBmatrix, Inc., 2005-2006.  All Rights Reserved.
-->
