=== xbrles/pgc2007/resources/System/VOPatterns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 The contents of this file are subject to the UBmatrix License Version 1.0 (the "License");
 you may not use this file except in compliance with the License. You may obtain a copy of the
 License at http://www.ubmatrix.com/prospect/eula_processor.asp

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 Copyright (c) UBmatrix, Inc., 2005-2006.  All Rights Reserved.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<!-- MSXML parser broken, currently not setting
     the default namespace
    xmlns:ps="http://www.ubmatrix.com/core/patternset"
    targetNamespace="http://www.ubmatrix.com/core/patternset"
-->
	<xs:simpleType name="detectionTypeEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="Discovery"/>
			<xs:enumeration value="InitialLoad"/>
			<xs:enumeration value="FinalLoad"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="patternMethodEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="XPath"/>
			<xs:enumeration value="TestRootSubstitutionGroupConstant"/>
			<xs:enumeration value="runOnce"/>
			<xs:enumeration value="FindTaxonomyTupleChildren"/>
			<xs:enumeration value="LocateItemConceptForValueObject"/>
			<xs:enumeration value="LocateTupleConceptForValueObject"/>
			<xs:enumeration value="LocateNonConceptForValueObject"/>
			<xs:enumeration value="ProcessImplicitReferences"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="actionMethodEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="CreateDomainObject"/>
			<xs:enumeration value="CreateRelationship"/>
			<xs:enumeration value="LoadSchemasFromSchemaLocation"/>
			<xs:enumeration value="LoadSchemaFromNamespace"/>
			<xs:enumeration value="LoadSchemaFromLogicalUri"/>
			<xs:enumeration value="LoadSchemaFromXmlBase"/>
			<xs:enumeration value="LoadSchemaConstant"/>
			<xs:enumeration value="SetOnLocationHandle"/>
			<xs:enumeration value="LoadLinkbaseFromLogicalUri"/>
			<xs:enumeration value="LoadLinkbaseFromXmlBase"/>
			<xs:enumeration value="AddToNamespaceResolver"/>
			<xs:enumeration value="AddToNamespaceLookup"/>
			<xs:enumeration value="CreateWarningMemo"/>
			<xs:enumeration value="CreateErrorMemo"/>
			<xs:enumeration value="ThrowException"/>
			<xs:enumeration value="SetPrimaryDomainObject"/>
			<xs:enumeration value="HashLocatorLabel"/>
			<xs:enumeration value="HashResourceLabel"/>
			<xs:enumeration value="IncludeSchemaFromXmlBase"/>
			<xs:enumeration value="IncludeSchemaFromLogicalUri"/>
			<xs:enumeration value="ResetLinkScoping"/>
			<xs:enumeration value="IsTaxonomy"/>
			<xs:enumeration value="IsLinkbase"/>
			<xs:enumeration value="IsInstance"/>
			<xs:enumeration value="FixXLinkCrossProduct"/>
			<xs:enumeration value="ResetArcScoping"/>
			<xs:enumeration value="QuickLink"/>
			<xs:enumeration value="ProcessArcroles"/>
			<xs:enumeration value="ProcessRoles"/>
			<xs:enumeration value="ProcessTaxonomy"/>
			<xs:enumeration value="DetermineDatatypeDerivation"/>
			<xs:enumeration value="ConnectDimensionsToTypedDomains"/>
			<xs:enumeration value="HookupDimensionalCharacterization"/>
			<xs:enumeration value="ProcessInstanceDocument"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="selectorTypeEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="ValueObject"/>
			<xs:enumeration value="From"/>
			<xs:enumeration value="To"/>
			<xs:enumeration value="Prefix"/>
			<xs:enumeration value="Namespace"/>
			<xs:enumeration value="IgnoreWhenProcessing"/>
			<xs:enumeration value="LogicalUri"/>
			<xs:enumeration value="XmlBase"/>
			<xs:enumeration value="SchemaLocationPairs"/>
			<xs:enumeration value="FromLabel"/>
			<xs:enumeration value="ToLabel"/>
			<xs:enumeration value="Link"/>
			<xs:enumeration value="Arc"/>
			<xs:enumeration value="FileType"/>
			<xs:enumeration value="Linkbase"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="queryPartMethodEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="XPath"/>
			<xs:enumeration value="Constant"/>
			<xs:enumeration value="NamespaceNode"/>
			<xs:enumeration value="Object"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="selectorMethodEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="Constant"/>
			<xs:enumeration value="XPath"/>
			<xs:enumeration value="DomainObject"/>
			<xs:enumeration value="DtsXPath"/>
			<xs:enumeration value="XPathId"/>
			<xs:enumeration value="DtsXPath-ResolveNamespace"/>
			<xs:enumeration value="DtsFindSchemaDomainObject"/>
			<xs:enumeration value="DtsConstant"/>
			<xs:enumeration value="NamespaceNode"/>
			<xs:enumeration value="DtsWithLogicalUriTranslateToPhysicalUri"/>
			<xs:enumeration value="DomainObjectFromValueObjectXPath"/>
			<xs:enumeration value="XPathWithTruncating"/>
			<xs:enumeration value="ReferencedDomainObject"/>
			<xs:enumeration value="SubstitutionGroupHeadIsItem"/>
			<xs:enumeration value="SubstitutionGroupHeadIsTuple"/>
			<xs:enumeration value="SubstitutionGroupHeadIsPart"/>
			<xs:enumeration value="LocatorFromLabel"/>
			<xs:enumeration value="ResourceFromLabel"/>
			<xs:enumeration value="ActualFileType"/>
			<xs:enumeration value="AttributeValueWithTruncating"/>
			<xs:enumeration value="AttributeValue"/>
			<xs:enumeration value="AttributeAncesterOrSelf"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ComplexSelectorPartMethodEnumeration">
		<xs:restriction base="xs:token">
			<xs:enumeration value="XPath"/>
			<xs:enumeration value="LogicalUri"/>
			<xs:enumeration value="LocatorFromLabel"/>
			<xs:enumeration value="ResourceFromLabel"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="SelectorAttributeGroup">
		<xs:attribute name="method" type="selectorMethodEnumeration" use="required"/>
		<xs:attribute name="value" type="xs:token" use="required"/>
	</xs:attributeGroup>
	<xs:complexType name="SelectorType">
		<xs:attribute name="type" type="selectorTypeEnumeration" use="required"/>
		<xs:attribute name="method" type="selectorMethodEnumeration" use="required"/>
		<xs:attribute name="value" type="xs:token" use="required"/>
	</xs:complexType>
	<xs:complexType name="ComplexSelectorType">
		<xs:sequence>
			<xs:element name="SelectorPart" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="method" type="ComplexSelectorPartMethodEnumeration" use="required"/>
					<xs:attribute name="value" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="selectorTypeEnumeration" use="required"/>
		<xs:attribute name="method" type="selectorMethodEnumeration" use="required"/>
	</xs:complexType>
	<xs:complexType name="FailureSelectorType">
		<xs:attribute name="method" type="selectorMethodEnumeration" use="required"/>
		<xs:attribute name="value" type="xs:token" use="required"/>
	</xs:complexType>
	<xs:complexType name="FailureType">
		<xs:sequence>
			<xs:element name="Action" type="ActionType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ActionType">
		<xs:sequence>
			<xs:element name="DtsQueryPredicate" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="QueryPart" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="method" type="queryPartMethodEnumeration" use="required"/>
								<xs:attribute name="value" type="xs:token" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="dtsRecursion" type="xs:boolean" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Selector" type="SelectorType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ComplexSelector" type="ComplexSelectorType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Failure" type="FailureType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:token" use="optional"/>
		<xs:attribute name="saveDO" type="xs:token" use="optional"/>
		<xs:attribute name="uri" type="xs:token" use="required"/>
		<xs:attribute name="method" type="actionMethodEnumeration" use="required"/>
		<xs:attribute name="indexByValueObject" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="PatternType">
		<xs:sequence>
			<xs:element name="Failure" type="FailureType" minOccurs="0"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="Action" type="ActionType"/>
				<xs:element name="Pattern" type="PatternType"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="name" type="xs:token" use="required"/>
		<xs:attribute name="detectionType" type="detectionTypeEnumeration" use="required"/>
		<xs:attribute name="method" type="patternMethodEnumeration" use="required"/>
		<xs:attribute name="value" type="xs:token" use="required"/>
	</xs:complexType>
	<xs:element name="PatternSet">
		<xs:annotation>
			<xs:documentation>The Patterns for ValueObjects</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pattern" type="PatternType" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:token" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== xbrles/pgc2007/resources/System/LinkbaseVOPatterns.xml
<?xml version="1.0" encoding="utf-8" ?> 

<PatternSet
    name="LinkbaseVOs"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="VOPatterns.xsd">

    <Pattern name="Load Namespace Resolvers" detectionType="Discovery" method="runOnce" value="N/A">
        <Failure />
        <Action method="AddToNamespaceResolver" uri="N/A">
            <Selector type="Prefix" method="Constant" value="link" />
            <Selector type="Namespace" method="Constant" value="http://www.xbrl.org/2003/linkbase" />
        </Action>
        <Action method="AddToNamespaceResolver" uri="N/A">
	        <Selector type="Prefix" method="Constant" value="xlink" />
	        <Selector type="Namespace" method="Constant" value="http://www.w3.org/1999/xlink" />
    	</Action>
        <Action method="AddToNamespaceResolver" uri="N/A">
            <Selector type="Prefix" method="Constant" value="xs" />
            <Selector type="Namespace" method="Constant" value="http://www.w3.org/2001/XMLSchema" />
    	</Action>
        <Action method="AddToNamespaceResolver" uri="N/A">
            <Selector type="Prefix" method="Constant" value="xbrli" />
            <Selector type="Namespace" method="Constant" value="http://www.xbrl.org/2003/instance" />
        </Action>
    </Pattern>

    <Pattern name="Discover schemas via 'schemaLocation'" detectionType="Discovery" method="XPath" value="/link:linkbase/@xsi:schemaLocation">
        <Failure />
        <Action method="LoadSchemasFromSchemaLocation" uri="N/A" >
            <Selector type="SchemaLocationPairs" method="XPath" value="." />
            <Failure>
                <Action saveDO="memo" method="CreateWarningMemo" uri="memo://ubmatrix.com/Load/Taxonomy#UnableToLocateOneOrMoreOfTheXsiSchemaLocationFiles"/>
            </Failure>
        </Action>
    </Pattern>

    <!-- Removed this unused relationship for performance
    <Pattern name="Load schemas via 'schemaLocation'" detectionType="Load" method="XPath" value="//@xsi:schemaLocation">
        <Action method="CreateRelationship" uri="relationship://ubmatrix.com/Xbrl/Relationship#SchemaReference">
            <Selector type="From" method="DomainObject" value="instance" />
            <Selector type="To" method="ReferencedDomainObject" value="N/A" />
        </Action>
    </Pattern>
    -->   

   <Pattern name="Find Implicit References" detectionType="Discovery" method="ProcessImplicitReferences" value="xlink:href">
        <Failure />
		<Action method="LoadSchemaFromXmlBase" uri="N/A">
       		<Selector type="LogicalUri" method="AttributeValueWithTruncating" value="xlink:href"/>
       		<Selector type="XmlBase" method="AttributeAncesterOrSelf" value="xml:base" />
       		<Failure>
            <Action method="LoadSchemaFromLogicalUri" uri="N/A">
   	     	     <Selector type="LogicalUri" method="AttributeValueWithTruncating" value="xlink:href"/>
    	         <Failure>
                     	<Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Load/Taxonomy#ImplicitSchemaReferenceFailedWithXmlBase">
                           	<Selector type="ValueObject" method="AttributeAncesterOrSelf" value="xml:base" />
                           	<Selector type="ValueObject" method="AttributeValue" value="xlink:href"/>
                           	<Failure>
                              	<Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Load/Taxonomy#ImplicitSchemaReferenceFailedLogicalUriOnly">
                                  	<Selector type="ValueObject" method="AttributeValue" value="xlink:href"/>
                                   	<Failure>
                                       	<Action saveDO="memo" method="CreateErrorMemo" uri="memo://ubmatrix.com/Load/Taxonomy#ImplicitSchemaReferenceFailedConfused"/>
                                   	</Failure>
                               	</Action>
                            </Failure>
                        </Action>
                     </Failure>
                </Action>
            </Failure>
         </Action>
    </Pattern>

    <Pattern name="Discover external linkbase" detectionType="Discovery" method="XPath"
             value="/link:linkbase">
        <Failure />
        <Action saveDO="linkbase" method="CreateDomainObject" uri="domain://ubmatrix.com/Xbrl/Linkbase#ExternalLinkbase">
            <Selector type="ValueObject" method="XPath" value="."/>
        </Action>
        <Action method="SetPrimaryDomainObject" uri="N/A">
            <Selector type="From" method="DomainObject" value="linkbase" />
        </Action>
    </Pattern>

    <Pattern name="Discover internal linkbase" detectionType="Discovery" method="XPath"
             value="/xs:schema/xs:annotation/xs:appinfo/link:linkbase">
        <Failure />
        <Action saveDO="linkbase" method="CreateDomainObject" uri="domain://ubmatrix.com/Xbrl/Linkbase#InternalLinkbase">
            <Selector type="ValueObject" method="XPath" value="."/>
        </Action>
    </Pattern>

    <Pattern name="Load linkbase" detectionType="FinalLoad" method="XPath"
             value="/link:linkbase | /xs:schema/xs:annotation/xs:appinfo/link:linkbase">
        
        <Failure />

        <Pattern name="Find link" detectionType="FinalLoad"  method="XPath" value="*[@xlink:type=&quot;extended&quot;]">
            <Failure />

            <Action method="QuickLink" uri="N/A">
                <Selector type="ValueObject" method="XPath" value="."/>
                <Selector type="Linkbase" method="DomainObjectFromValueObjectXPath" value=".."/>
            </Action>

        </Pattern>

    </Pattern>

    <!-- Footnote Linkbases don't have a VO (and don't need pre-discovery -->
    <Pattern name="Load Footnote Linkbase" detectionType="FinalLoad" method="XPath"
             value="/xbrli:xbrl[link:footnoteLink]">
        
        <Failure />

        <Action saveDO="linkbase" method="CreateDomainObject" uri="domain://ubmatrix.com/Xbrl/Linkbase#InternalFootnoteLinkbase" />

        <Action method="CreateRelationship" uri="relationship://ubmatrix.com/Xbrl/Relationship#InstanceReferencesLinkbase">
            <Selector type="From" method="DomainObjectFromValueObjectXPath" value="." />
            <Selector type="To" method="DomainObject" value="linkbase" />
        </Action>
   
        <Pattern name="Find link" detectionType="FinalLoad" method="XPath" value="*[@xlink:type=&quot;extended&quot;]">
            <Failure />

            <Action method="QuickLink" uri="N/A">
                <Selector type="ValueObject" method="XPath" value="."/>
                <Selector type="Linkbase" method="DomainObject" value="linkbase"/>
            </Action>

        </Pattern>

    </Pattern>


    <Pattern name="Find objects classified by role or arcrole" detectionType="FinalLoad" method="XPath" value="/">
        <Action method="ProcessArcroles" uri="N/A">
            <Selector type="ValueObject" method="XPath" value="." />
        </Action>
        <Action method="ProcessRoles" uri="N/A">
            <Selector type="ValueObject" method="XPath" value="." />
        </Action>
    </Pattern>

    <Pattern name="Create namespaces" detectionType="FinalLoad" method="XPath"
             value="/link:linkbase/namespace::node()[name()!= '']">
        <Failure />

        <Action method="AddToNamespaceLookup" uri="N/A">
            <Selector type="Prefix" method="NamespaceNode" value="name" />
            <Selector type="Namespace" method="NamespaceNode" value="value" />
        </Action>

        <Action saveDO="namespace" method="CreateDomainObject" uri="domain://ubmatrix.com/Xbrl/Namespace#Namespace">
            <Selector type="ValueObject" method="XPath" value="."/>
        </Action>

        <Action saveDO="prefix" method="CreateDomainObject" uri="domain://ubmatrix.com/Xbrl/Namespace#NamespacePrefix">
            <Selector type="ValueObject" method="XPath" value="."/>
        </Action>

        <Action saveDO="trn" method="CreateRelationship" uri="relationship://ubmatrix.com/Xbrl/Linkbase/Relationship#LinkbaseReferencesNamespace">
            <Selector type="From" method="DomainObject" value="linkbase" />
            <Selector type="To" method="DomainObject" value="namespace" />
        </Action>

        <Action method="CreateRelationship" uri="relationship://ubmatrix.com/Xbrl/Linkbase/Relationship#LinkbaseNamespaceHasPrefix">
            <Selector type="From" method="DomainObject" value="trn" />
            <Selector type="To" method="DomainObject" value="prefix" />
        </Action>
    </Pattern>


</PatternSet>

<!--
 The contents of this file are subject to the UBmatrix License Version 1.0 (the "License");
 you may not use this file except in compliance with the License. You may obtain a copy of the
 License at http://www.ubmatrix.com/prospect/eula_processor.asp

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 Copyright (c) UBmatrix, Inc., 2005-2006.  All Rights Reserved.
-->

=== xbrles/pgc2007/resources/System/PeekPatterns.xml
<?xml version="1.0" encoding="utf-8" ?> 

<PatternSet
    name="TaxonomyVOs"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="VOPatterns.xsd">

    <Pattern name="Load Namespace Resolvers" detectionType="Discovery" method="runOnce" value="N/A">
        <Failure>
                <Action method="ThrowException" uri="memo://ubmatrix.com/Load/Taxonomy#Internal-NamespaceResolverFailure" />
        </Failure>
        <Action method="AddToNamespaceResolver" uri="N/A">
            <Selector type="Prefix" method="Constant" value="xs" />
            <Selector type="Namespace" method="Constant" value="http://www.w3.org/2001/XMLSchema" />
        </Action>
        <Action method="AddToNamespaceResolver" uri="N/A">
            <Selector type="Prefix" method="Constant" value="link" />
            <Selector type="Namespace" method="Constant" value="http://www.xbrl.org/2003/linkbase" />
        </Action>
        <Action method="AddToNamespaceResolver" uri="N/A">
            <Selector type="Prefix" method="Constant" value="xsi" />
            <Selector type="Namespace" method="Constant" value="http://www.w3.org/2001/XMLSchema-instance" />
        </Action>
        <Action method="AddToNamespaceResolver" uri="N/A">
            <Selector type="Prefix" method="Constant" value="xlink" />
            <Selector type="Namespace" method="Constant" value="http://www.w3.org/1999/xlink" />
        </Action>
        <Action method="AddToNamespaceResolver" uri="N/A">
	    <Selector type="Prefix" method="Constant" value="xbrli" />
	    <Selector type="Namespace" method="Constant" value="http://www.xbrl.org/2003/instance" />
	</Action>
    </Pattern>

    <Pattern name="Peek Taxonomy" detectionType="Discovery" method="XPath" value="/xs:schema">
        <Action method="IsTaxonomy" uri="N/A">
        	<Failure>
                    <Action saveDO="memo" method="CreateWarningMemo" uri="memo://ubmatrix.com/Peek/Peek#DifferentFromExpectType">
		            <Selector type="FileType" method="ActualFileType" value="."/>
                            <Selector type="FileType" method="Constant" value="Taxonomy"/>
                    </Action>
          	</Failure>
        </Action>
    </Pattern>

    <Pattern name="Peek Linkbase" detectionType="Discovery" method="XPath" value="/link:linkbase">
        <Action method="IsLinkbase" uri="N/A">
        	<Failure>
                    <Action saveDO="memo" method="CreateWarningMemo" uri="memo://ubmatrix.com/Peek/Peek#DifferentFromExpectType">
		            <Selector type="FileType" method="ActualFileType" value="."/>
                            <Selector type="FileType" method="Constant" value="Linkbase"/>
                    </Action>
          	</Failure>
        </Action>
    </Pattern>

    <Pattern name="Peek Instance" detectionType="Discovery" method="XPath" value="/xbrli:xbrl">
        <Action method="IsInstance" uri="N/A">
        	<Failure>
                    <Action saveDO="memo" method="CreateWarningMemo" uri="memo://ubmatrix.com/Peek/Peek#DifferentFromExpectType">
		            <Selector type="FileType" method="ActualFileType" value="."/>
                            <Selector type="FileType" method="Constant" value="Instance"/>
                    </Action>
          	</Failure>
        </Action>
    </Pattern>
</PatternSet>

<!--
 The contents of this file are subject to the UBmatrix License Version 1.0 (the "License");
 you may not use this file except in compliance with the License. You may obtain a copy of the
 License at http://www.ubmatrix.com/prospect/eula_processor.asp

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 Copyright (c) UBmatrix, Inc., 2005-2006.  All Rights Reserved.
-->
